services:
  app:
    image: ghcr.io/adamalfiansyah/belajar-docker/app:latest
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        ENVIRONMENT: production
    container_name: ${APP_SERVICE_NAME}
    ports:
      - "${APP_PORT}:9000"
    depends_on:
      - mysql

  nginx:
    image: ghcr.io/adamalfiansyah/belajar-docker/laravel-nginx:latest
    container_name: ${NGINX_SERVICE_NAME}
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_SERVICE_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  db_data:
