services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        ENVIRONMENT: production
    image: ${APP_IMAGE}
    container_name: ${APP_SERVICE_NAME}
    ports:
      - "${APP_PORT}:9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: ${NGINX_SERVICE_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_SERVICE_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  db_data: